LICENSE

Relicense under Apache-2.0

---

.github/workflows/test.yml

Run [ShellCheck](https://www.shellcheck.net/) tests against `src/` folder.

Run shellcheck as part of CI

---

.github/workflows/build.yml
README.md
action.yml
examples/tf12_config/.terraform-docs.yml
examples/tf12_config/README.md
examples/tf12_config/main.tf
scripts/pre-release.sh
scripts/release.sh
scripts/update-readme.sh
src/docker-entrypoint.sh

Add support new parameter `config-file` for passing down `.terraform-docs.yml` config file.

Add support for terraform-docs config file

---

README.md

chore: prepare release v0.2.0

---

.github/workflows/build.yml
.github/workflows/test.yml

Make sure README is always updated. This means contributors have run `./scripts/update-readme.sh` locally after changing `actions.yml`.

Validate README is always up to date

---

README.md

chore: prepare release v0.3.0

---

.github/templates/README.tpl
.github/workflows/build.yml
.github/workflows/release-draft.yml
.github/workflows/test.yml
examples/README.md
scripts/pre-release.sh
scripts/release.sh

This PR applies the required changes for moving to `main` as the primary branch.
Fixes #19

Rename official branch to 'main'

---

README.md

chore: prepare release v0.4.0

---

.github/pull_request_template.md
CONTRIBUTING.md
DCO
LICENSE
scripts/pre-release.sh
scripts/release.sh
scripts/update-readme.sh
src/docker-entrypoint.sh

Housekeeping items:
- Add DCO file
- Add license header to relevant files
- Add contribution guide
- Update pull request template

Repositiory housekeeping items

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/templates/README.tpl
CONTRIBUTING.md
Dockerfile
README.md

Fix some chores:
- Add missing license header to `Dockerfile`
- Add Slack workspace link
- Cleanup README and its template
I have:

Update README and add missing links

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CONTRIBUTING.md

Update Slack URL.
I have:
Not applicable.

Update Slack URL

---

.github/templates/README.tpl
.github/workflows/build.yml
Dockerfile
README.md
examples/tf11_basic/USAGE.md
examples/tf11_extra_args/USAGE.md
examples/tf12_basic/README.md
examples/tf12_find/USAGE.md
examples/tf12_find/modules/tf12_find_submodules/USAGE.md
examples/tf12_inject/README.md

Update terraform-docs to v0.11.0

---

.github/templates/README.tpl
Dockerfile
README.md
examples/tf11_basic/USAGE.md
examples/tf11_extra_args/USAGE.md
examples/tf12_basic/README.md
examples/tf12_find/USAGE.md
examples/tf12_inject/README.md

Update terraform-docs to v0.11.2

---

.github/templates/README.tpl
.github/workflows/build.yml
Dockerfile
README.md
examples/tf11_basic/USAGE.md
examples/tf11_extra_args/USAGE.md
examples/tf12_basic/README.md
examples/tf12_config/README.md
examples/tf12_fail_diff/README.md
examples/tf12_find/USAGE.md
examples/tf12_find/modules/tf12_find_submodules/USAGE.md
examples/tf12_inject/README.md

Update terraform-docs to v0.12.0

---

.github/workflows/ci.yml
examples/tf12_atlantis/README.md
src/docker-entrypoint.sh

There are some breaking changes in yq moving from `v3` to `v4`, which this PR addresses it.
Fixes #31
I have:
Let the CI run and make sure `Should generate README.md for tf12_atlantis` step passes.

Move to yq v4 syntax

---

.github/templates/README.tpl
Dockerfile
README.md

Update terraform-docs to v0.12.1

---

README.md

chore: prepare release v0.6.1

---

.github/templates/README.tpl
Dockerfile
README.md
examples/tf12_config/.terraform-docs.yml
src/docker-entrypoint.sh

Update terraform-docs to v0.13.0

---

scripts/pre-release.sh

Update docker tag in action.yml on release

---

Dockerfile

Adds `git-lfs` to the built Docker image. See terraform-docs/gh-actions#44.
I have:
I built the image locally and tested it out.

Include git-lfs in Docker image

---

Dockerfile

Ensure yq v4.x is installed in the image

---

.github/workflows/test.yml
scripts/pre-release.sh
scripts/release.sh
scripts/update-readme.sh
src/docker-entrypoint.sh

Format all shell scripts

---

examples/tf11_extra_args/USAGE.md
src/docker-entrypoint.sh

Use provided template in replace mode too

---

README.md
action.yml

chore: prepare release v0.7.0

---

.github/templates/README.tpl
Dockerfile
README.md

Upgrade terraform-docs to v0.14.0

---

README.md
action.yml

chore: prepare release v0.8.0

---

.github/templates/README.tpl
Dockerfile
README.md

feat: update terraform-docs to 0.14.1

---

.github/workflows/ci.yml
README.md
action.yml

chore: prepare release v0.9.0

---

.github/templates/README.tpl
.github/workflows/ci.yml
Dockerfile
README.md
examples/tf12_inject/README.md

Upgrade terraform-docs to v0.15.0

---

README.md
action.yml

chore: prepare release v0.10.0

---

src/docker-entrypoint.sh

Fixes #64 
I have:
I'm not sure on the best way to test this. What would you recommend?
It would be helpful if the testing process was described in the Contributing Proces.

fix: always set num_changed output

---

README.md
action.yml

chore: prepare release v0.11.0

---

.github/workflows/ci.yml
README.md
action.yml
src/docker-entrypoint.sh

Add recursive and recursive path to action

---

.github/templates/README.tpl
.github/workflows/ci.yml
README.md
action.yml
examples/tf11_basic/README.md
examples/tf11_extra_args/README.md
examples/tf12_atlantis/README.md
examples/tf12_basic/README.md
examples/tf12_config/README.md
examples/tf12_fail_diff/README.md
examples/tf12_find/README.md
examples/tf12_inject/README.md

Change default output-file to README.md

---

.github/templates/README.tpl
README.md
action.yml

chore: prepare release v1.0.0

---

.github/dependabot.yml

chore: Add dependabot file

---

.github/templates/README.tpl
Dockerfile
README.md
src/docker-entrypoint.sh

Update terraform-docs to v0.17.0

---

Dockerfile

Previously we had to add additional repository to be able to install `yq`  from. But now `alpine` image already has the package `yq` ready to be installed.
Fixes #99
I have:

feat: install yq directly from alpine without extra repo

---

.github/templates/README.tpl
Dockerfile
README.md
action.yml

chore: prepare release v1.2.0

---

README.md
action.yml

Bumping the version in order to fix the bogus 1.2.1 release. :(

Bump to v1.2.2

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml

fix: use hardcoded name for the docker image org

---

action.yml

chore: update and simplify action name
